<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import {
  PhArrowClockwise, PhChartLineUp, PhCheck, PhCirclesThreePlus, PhClock,
  PhHouse, PhListChecks, PhPackage, PhPlus, PhSignOut, PhSoccerBall,
  PhTrash, PhUsersThree, PhX,
} from '@phosphor-icons/vue'
import BrandMark from '../components/BrandMark.vue'
import StatePanel from '../components/StatePanel.vue'
import { api } from '../api/client'
import { useAuthStore } from '../stores/auth'

const auth = useAuthStore()
const section = ref('overview'), loading = ref(true), saving = ref(false), error = ref(''), notice = ref('')
const metrics = ref({}), packages = ref([]), predictions = ref([]), subscriptions = ref([]), wins = ref([]), testimonials = ref([]), customers = ref([]), activities = ref([])
const packageFile = ref(null), winFile = ref(null), confirmation = ref(null)
const sections = [
  { id:'overview', label:'Overview', note:'Operating pulse', icon:PhHouse },
  { id:'predictions', label:'Predictions', note:'Publish the board', icon:PhSoccerBall },
  { id:'packages', label:'Packages', note:'Plans and access', icon:PhPackage },
  { id:'access', label:'Access queue', note:'Approve members', icon:PhListChecks },
  { id:'content', label:'Proof & voices', note:'Wins and testimonials', icon:PhCirclesThreePlus },
  { id:'members', label:'Members', note:'Audience controls', icon:PhUsersThree },
  { id:'activity', label:'Activity', note:'System audit trail', icon:PhClock },
]
const activeMeta = computed(() => sections.find((item)=>item.id===section.value))
const pending = computed(()=>subscriptions.value.filter((item)=>item.status==='pending'))
const packageForm = reactive({ name:'', slug:'', description:'', price:'', currency:'UGX', duration_days:1, access_label:'Premium predictions', benefits:'', is_active:true, is_featured:false, display_order:0 })
const predictionForm = reactive({ home_team:'', away_team:'', competition:'', kickoff_at:'', access_level:'free', package:null, market:'', selection:'', odds:'', confidence:70, analysis:'', result:'pending', is_published:true })
const winForm = reactive({ title:'', summary:'', odds:'', settled_at:'', is_published:true })
const testimonialForm = reactive({ member_name:'', quote:'', member_since:'', is_published:true, display_order:0 })
const money=(value)=>new Intl.NumberFormat('en-UG').format(value||0)
const formatDate=(value)=>value?new Intl.DateTimeFormat('en-UG',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'Not set'

async function loadAll(){loading.value=true;error.value='';try{const data=await Promise.all([
  api('/v1/owner/dashboard/'),api('/v1/owner/packages/'),api('/v1/owner/predictions/'),api('/v1/owner/subscriptions/'),api('/v1/owner/recent-wins/'),api('/v1/owner/testimonials/'),api('/v1/owner/customers/'),api('/v1/owner/activities/'),
]);[metrics.value,packages.value,predictions.value,subscriptions.value,wins.value,testimonials.value,customers.value,activities.value]=data}catch(e){error.value=e.message}finally{loading.value=false}}
function flash(text){notice.value=text;setTimeout(()=>{notice.value=''},3500)}
async function createPackage(){saving.value=true;error.value='';try{const data=new FormData();Object.entries(packageForm).forEach(([key,value])=>data.append(key,key==='benefits'?JSON.stringify(value.split('\n').map(x=>x.trim()).filter(Boolean)):value));if(packageFile.value)data.append('image',packageFile.value);await api('/v1/owner/packages/',{method:'POST',body:data});Object.assign(packageForm,{name:'',slug:'',description:'',price:'',currency:'UGX',duration_days:1,access_label:'Premium predictions',benefits:'',is_active:true,is_featured:false,display_order:0});packageFile.value=null;flash('Package published.');await loadAll()}catch(e){error.value=e.message}finally{saving.value=false}}
async function createPrediction(){saving.value=true;error.value='';try{const payload={...predictionForm,kickoff_at:new Date(predictionForm.kickoff_at).toISOString(),package:predictionForm.access_level==='premium'?predictionForm.package:null,odds:predictionForm.odds||null};await api('/v1/owner/predictions/',{method:'POST',body:JSON.stringify(payload)});Object.assign(predictionForm,{home_team:'',away_team:'',competition:'',kickoff_at:'',access_level:'free',package:null,market:'',selection:'',odds:'',confidence:70,analysis:'',result:'pending',is_published:true});flash('Prediction added to the board.');await loadAll()}catch(e){error.value=e.message}finally{saving.value=false}}
async function togglePackage(plan,field){try{await api(`/v1/owner/packages/${plan.id}/`,{method:'PATCH',body:JSON.stringify({[field]:!plan[field]})});flash('Package updated.');await loadAll()}catch(e){error.value=e.message}}
async function settlePrediction(pick,result){try{await api(`/v1/owner/predictions/${pick.id}/`,{method:'PATCH',body:JSON.stringify({result})});flash(`Prediction marked ${result}.`);await loadAll()}catch(e){error.value=e.message}}
async function decide(sub,decision){saving.value=true;try{await api(`/v1/owner/subscriptions/${sub.id}/decide/`,{method:'POST',body:JSON.stringify({decision})});flash(`Access ${decision === 'approve' ? 'approved' : decision + 'led'}.`);await loadAll()}catch(e){error.value=e.message}finally{saving.value=false}}
async function createWin(){saving.value=true;try{const data=new FormData();Object.entries(winForm).forEach(([k,v])=>data.append(k,k==='settled_at'?new Date(v).toISOString():v));if(winFile.value)data.append('image',winFile.value);await api('/v1/owner/recent-wins/',{method:'POST',body:data});Object.assign(winForm,{title:'',summary:'',odds:'',settled_at:'',is_published:true});flash('Result published.');await loadAll()}catch(e){error.value=e.message}finally{saving.value=false}}
async function createTestimonial(){saving.value=true;try{await api('/v1/owner/testimonials/',{method:'POST',body:JSON.stringify(testimonialForm)});Object.assign(testimonialForm,{member_name:'',quote:'',member_since:'',is_published:true,display_order:0});flash('Testimonial published.');await loadAll()}catch(e){error.value=e.message}finally{saving.value=false}}
async function toggleBlock(customer){try{await api(`/v1/owner/customers/${customer.id}/block/`,{method:'POST',body:JSON.stringify({blocked:!customer.is_blocked})});await loadAll()}catch(e){error.value=e.message}}
function requestDelete(label,path){confirmation.value={label,path}}
async function confirmDelete(){if(!confirmation.value)return;try{await api(confirmation.value.path,{method:'DELETE'});flash(`${confirmation.value.label} removed.`);confirmation.value=null;await loadAll()}catch(e){error.value=e.message}}
onMounted(loadAll)
</script>

<template>
  <div class="owner-shell">
    <aside class="owner-sidebar">
      <BrandMark />
      <p class="owner-label">Owner control room</p>
      <nav><button v-for="item in sections" :key="item.id" :class="{active:section===item.id}" @click="section=item.id"><component :is="item.icon" :size="20"/><span><strong>{{ item.label }}</strong><small>{{ item.note }}</small></span></button></nav>
      <div class="owner-identity"><span>{{ auth.user?.full_name?.charAt(0) }}</span><div><strong>{{ auth.user?.full_name }}</strong><small>Owner access</small></div></div>
      <button class="owner-signout" @click="auth.logout"><PhSignOut :size="18"/> Sign out</button>
    </aside>

    <main class="owner-main">
      <header class="owner-header"><div><p>BK / OPERATIONS</p><h1>{{ activeMeta.label }}</h1><span>{{ activeMeta.note }}</span></div><button class="icon-button" title="Refresh data" @click="loadAll"><PhArrowClockwise :size="20"/></button></header>
      <div class="owner-content">
        <div v-if="notice" class="toast"><PhCheck :size="18"/>{{ notice }}</div>
        <StatePanel v-if="error" title="The control room needs attention" :message="error" tone="error"><button class="text-button" @click="error=''">Dismiss</button></StatePanel>
        <div v-if="loading" class="owner-loading"><span></span><p>Syncing the control room…</p></div>

        <template v-else-if="section==='overview'">
          <div class="owner-kpis"><article><span>Audience</span><strong>{{ metrics.customers }}</strong><small>registered members</small></article><article class="attention"><span>Access queue</span><strong>{{ metrics.pending_requests }}</strong><small>awaiting decision</small></article><article><span>Live access</span><strong>{{ metrics.active_subscriptions }}</strong><small>active subscriptions</small></article><article><span>Board</span><strong>{{ metrics.published_predictions }}</strong><small>published predictions</small></article></div>
          <div class="owner-grid"><section class="owner-panel wide"><div class="panel-heading"><div><p>Package signal</p><h2>Demand by access plan</h2></div><PhChartLineUp :size="24"/></div><div class="demand-list"><div v-for="plan in metrics.package_demand" :key="plan.id"><strong>{{ plan.name }}</strong><span><i :style="{width:`${Math.min(100,plan.request_count*12)}%`}"></i></span><b>{{ plan.request_count }} requests / {{ plan.active_count }} active</b></div></div></section><section class="owner-panel"><div class="panel-heading"><div><p>Informational value</p><h2>Active access</h2></div></div><strong class="money-figure"><small>UGX</small>{{ money(metrics.informational_value) }}</strong><p class="muted">No payment is processed in the MVP. This is the listed value of manually activated access.</p></section></div>
          <section class="owner-panel"><div class="panel-heading"><div><p>Immediate queue</p><h2>Requests needing a decision</h2></div><button class="text-button" @click="section='access'">Open queue</button></div><div v-if="!pending.length" class="empty-row">The access queue is clear.</div><div v-else class="table-wrap"><table><thead><tr><th>Member</th><th>Package</th><th>Requested</th><th>Action</th></tr></thead><tbody><tr v-for="sub in pending.slice(0,5)" :key="sub.id"><td><strong>{{ sub.user.full_name }}</strong><small>{{ sub.user.phone }}</small></td><td>{{ sub.package.name }}</td><td>{{ formatDate(sub.requested_at) }}</td><td><button class="table-action approve" @click="decide(sub,'approve')">Approve</button></td></tr></tbody></table></div></section>
        </template>

        <template v-else-if="section==='packages'">
          <div class="owner-split"><section class="owner-panel form-panel"><div class="panel-heading"><div><p>New package</p><h2>Publish an access plan</h2></div><PhPlus :size="22"/></div><form class="owner-form" @submit.prevent="createPackage"><div class="field-pair"><label>Name<input v-model="packageForm.name" required placeholder="Weekend Board"></label><label>Slug<input v-model="packageForm.slug" required pattern="[a-z0-9-]+" placeholder="weekend-board"></label></div><label>Description<textarea v-model="packageForm.description" required rows="3" placeholder="Explain the working rhythm and value."></textarea></label><div class="field-pair"><label>Price (UGX)<input v-model="packageForm.price" required min="0" type="number"></label><label>Duration (days)<input v-model="packageForm.duration_days" required min="1" type="number"></label></div><label>Benefits <small>One per line</small><textarea v-model="packageForm.benefits" rows="4" placeholder="Daily shortlist&#10;Full market and odds"></textarea></label><label class="file-field">Package image<input type="file" accept="image/png,image/jpeg,image/webp" @change="packageFile=$event.target.files[0]"><span>{{ packageFile?.name || 'Choose a JPG, PNG or WebP' }}</span></label><div class="check-row"><label><input v-model="packageForm.is_active" type="checkbox"> Open for requests</label><label><input v-model="packageForm.is_featured" type="checkbox"> Feature this plan</label></div><button class="button primary full" :disabled="saving">{{ saving?'Publishing…':'Publish package' }}</button></form></section>
          <section class="owner-panel collection-panel"><div class="panel-heading"><div><p>Catalogue</p><h2>{{ packages.length }} access plans</h2></div></div><div class="owner-card-list"><article v-for="plan in packages" :key="plan.id"><div class="thumbnail" :style="plan.image_url?{backgroundImage:`url(${plan.image_url})`}:{}"><PhPackage v-if="!plan.image_url" :size="24"/></div><div><span :class="['status-dot-label',plan.is_active?'active':'']">{{ plan.is_active?'Open':'Closed' }}</span><h3>{{ plan.name }}</h3><p>{{ plan.duration_days }} days · UGX {{ money(plan.price) }}</p><div class="micro-actions"><button @click="togglePackage(plan,'is_active')">{{ plan.is_active?'Close requests':'Open requests' }}</button><button @click="togglePackage(plan,'is_featured')">{{ plan.is_featured?'Unfeature':'Feature' }}</button></div></div><button class="icon-button danger" title="Delete package" @click="requestDelete(plan.name,`/v1/owner/packages/${plan.id}/`)"><PhTrash :size="18"/></button></article></div></section></div>
        </template>

        <template v-else-if="section==='predictions'">
          <div class="owner-split prediction-workspace"><section class="owner-panel form-panel"><div class="panel-heading"><div><p>New board entry</p><h2>Publish a prediction</h2></div><PhSoccerBall :size="22"/></div><form class="owner-form" @submit.prevent="createPrediction"><div class="field-pair"><label>Home team<input v-model="predictionForm.home_team" required></label><label>Away team<input v-model="predictionForm.away_team" required></label></div><div class="field-pair"><label>Competition<input v-model="predictionForm.competition" required></label><label>Kickoff<input v-model="predictionForm.kickoff_at" required type="datetime-local"></label></div><div class="field-pair"><label>Access<select v-model="predictionForm.access_level"><option value="free">Free</option><option value="premium">Premium</option></select></label><label v-if="predictionForm.access_level==='premium'">Required package<select v-model="predictionForm.package" required><option :value="null" disabled>Select package</option><option v-for="plan in packages" :key="plan.id" :value="plan.id">{{ plan.name }}</option></select></label></div><div class="field-pair"><label>Market<input v-model="predictionForm.market" required placeholder="Match result"></label><label>Selection<input v-model="predictionForm.selection" required placeholder="Home win"></label></div><div class="field-pair"><label>Odds<input v-model="predictionForm.odds" min="1" step="0.01" type="number"></label><label>Confidence<input v-model="predictionForm.confidence" min="0" max="100" type="number"></label></div><label>Analysis<textarea v-model="predictionForm.analysis" rows="4"></textarea></label><div class="check-row"><label><input v-model="predictionForm.is_published" type="checkbox"> Publish immediately</label></div><button class="button primary full" :disabled="saving">Add to match board</button></form></section><section class="owner-panel collection-panel"><div class="panel-heading"><div><p>Match board</p><h2>{{ predictions.length }} entries</h2></div></div><div class="prediction-admin-list"><article v-for="pick in predictions" :key="pick.id"><span>{{ formatDate(pick.kickoff_at) }}</span><div><small>{{ pick.competition }} · {{ pick.access_level }}</small><h3>{{ pick.home_team }} <i>v</i> {{ pick.away_team }}</h3><p>{{ pick.market }} / {{ pick.selection }}</p><div class="micro-actions"><button @click="settlePrediction(pick,'won')">Won</button><button @click="settlePrediction(pick,'lost')">Lost</button><button @click="settlePrediction(pick,'void')">Void</button></div></div><b :class="pick.result">{{ pick.result }}</b><button class="icon-button danger" @click="requestDelete(`${pick.home_team} v ${pick.away_team}`,`/v1/owner/predictions/${pick.id}/`)"><PhTrash :size="17"/></button></article></div></section></div>
        </template>

        <template v-else-if="section==='access'">
          <section class="owner-panel"><div class="panel-heading"><div><p>Manual membership</p><h2>Access requests</h2></div><span class="queue-count">{{ pending.length }} pending</span></div><div class="table-wrap"><table><thead><tr><th>Member</th><th>Package</th><th>Value</th><th>Status</th><th>Requested</th><th>Decision</th></tr></thead><tbody><tr v-for="sub in subscriptions" :key="sub.id"><td><strong>{{ sub.user.full_name }}</strong><small>{{ sub.user.phone }}</small></td><td>{{ sub.package.name }}</td><td>UGX {{ money(sub.price_snapshot) }}</td><td><span :class="['status-chip',sub.status]">{{ sub.status }}</span></td><td>{{ formatDate(sub.requested_at) }}</td><td><div class="decision-actions" v-if="sub.status==='pending'"><button class="table-action approve" :disabled="saving" @click="decide(sub,'approve')">Approve</button><button class="table-action reject" :disabled="saving" @click="decide(sub,'reject')">Reject</button></div><button v-else-if="sub.status==='active'" class="table-action reject" @click="decide(sub,'cancel')">Cancel</button><span v-else>None</span></td></tr></tbody></table></div></section>
        </template>

        <template v-else-if="section==='content'">
          <div class="owner-split"><section class="owner-panel form-panel"><div class="panel-heading"><div><p>Recent result</p><h2>Publish a win</h2></div></div><form class="owner-form" @submit.prevent="createWin"><label>Title<input v-model="winForm.title" required></label><label>Summary<textarea v-model="winForm.summary" required rows="3"></textarea></label><div class="field-pair"><label>Combined odds<input v-model="winForm.odds" type="number" min="1" step="0.01"></label><label>Settled at<input v-model="winForm.settled_at" required type="datetime-local"></label></div><label class="file-field">Proof image<input type="file" accept="image/png,image/jpeg,image/webp" @change="winFile=$event.target.files[0]"><span>{{ winFile?.name || 'Choose optional media' }}</span></label><button class="button primary full" :disabled="saving">Publish result</button></form></section><section class="owner-panel form-panel"><div class="panel-heading"><div><p>Member voice</p><h2>Add a testimonial</h2></div></div><form class="owner-form" @submit.prevent="createTestimonial"><label>Member name<input v-model="testimonialForm.member_name" required></label><label>Quote<textarea v-model="testimonialForm.quote" required rows="5"></textarea></label><label>Member context<input v-model="testimonialForm.member_since" placeholder="Member since 2026"></label><button class="button primary full" :disabled="saving">Publish testimonial</button></form></section></div><div class="owner-grid"><section class="owner-panel wide"><div class="panel-heading"><div><p>Published proof</p><h2>Recent wins</h2></div></div><div class="simple-list"><div v-for="win in wins" :key="win.id"><span>{{ formatDate(win.settled_at) }}</span><strong>{{ win.title }}</strong><button class="icon-button danger" @click="requestDelete(win.title,`/v1/owner/recent-wins/${win.id}/`)"><PhTrash :size="16"/></button></div></div></section><section class="owner-panel"><div class="panel-heading"><div><p>Social proof</p><h2>Testimonials</h2></div></div><div class="simple-list"><div v-for="voice in testimonials" :key="voice.id"><strong>{{ voice.member_name }}</strong><span>{{ voice.quote.slice(0,55) }}…</span><button class="icon-button danger" @click="requestDelete(voice.member_name,`/v1/owner/testimonials/${voice.id}/`)"><PhTrash :size="16"/></button></div></div></section></div>
        </template>

        <template v-else-if="section==='members'">
          <section class="owner-panel"><div class="panel-heading"><div><p>Audience</p><h2>Registered members</h2></div><span>{{ customers.length }} total</span></div><div class="member-grid"><article v-for="customer in customers" :key="customer.id"><span>{{ customer.full_name.charAt(0) }}</span><div><h3>{{ customer.full_name }}</h3><p>{{ customer.phone }}</p><small>Joined {{ new Date(customer.created_at).toLocaleDateString('en-UG') }}</small></div><button :class="['table-action',customer.is_blocked?'approve':'reject']" @click="toggleBlock(customer)">{{ customer.is_blocked?'Restore':'Block' }}</button></article></div></section>
        </template>

        <template v-else-if="section==='activity'">
          <section class="owner-panel"><div class="panel-heading"><div><p>Audit trail</p><h2>Recent system activity</h2></div><span>{{ activities.length }} events</span></div><div v-if="!activities.length" class="empty-row">No activity has been recorded yet.</div><div v-else class="table-wrap"><table><thead><tr><th>When</th><th>Category</th><th>Actor</th><th>Activity</th><th>IP address</th></tr></thead><tbody><tr v-for="activity in activities" :key="activity.id"><td>{{ formatDate(activity.created_at) }}</td><td><span class="status-chip active">{{ activity.category }}</span></td><td><strong>{{ activity.actor_name || 'System' }}</strong><small>{{ activity.actor_phone }}</small></td><td>{{ activity.description }}</td><td>{{ activity.ip_address || 'Not recorded' }}</td></tr></tbody></table></div></section>
        </template>
      </div>
    </main>

    <div v-if="confirmation" class="confirm-layer" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><div class="confirm-box"><button class="icon-button" @click="confirmation=null"><PhX :size="18"/></button><p>Confirm removal</p><h2 id="confirm-title">Remove {{ confirmation.label }}?</h2><span>This action cannot be undone.</span><div><button class="button secondary" @click="confirmation=null">Keep it</button><button class="button destructive" @click="confirmDelete">Remove permanently</button></div></div></div>
  </div>
</template>
